spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  hibernate:
    ddl-auto: validate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml

logging:
  level:
    org.springframework: INFO
